version: '3'

services:
  proxy:
    image: nginx:1.12-alpine
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - web
  web:
    build: docker/apache
    volumes:
      - ./:/var/www/site

