version: '3'

services:

  proxy:
    image: nginx:1.12-alpine
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    volumes:
      - ./storage/app/public:/storage/app/public
      - ./public:/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - web

  web:
    build: docker/apache
    working_dir: /var/www/site
    volumes:
      - ./:/var/www/site
    links:
      - db
      - sphinx

  db:
    image: mysql:5.7
    volumes:
      - ./docker/runtime/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root

  sphinx:
    image: stefobark/sphinxdocker
    command: ./indexandsearch.sh
    volumes:
     - ./docker/sphinx:/etc/sphinxsearch
     - ./docker/runtime/sphinx:/var/lib/sphinx
    ports:
     - "9306:9306"
    links:
     - db