version: '3'

services:
  proxy:
    image: nginx:1.12-alpine
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    volumes:
      - ./public:/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - web
  web:
    build: docker/apache
    working_dir: /var/www/site
    volumes:
      - ./:/var/www/site
    links:
      - db

  db:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root